### ISSUE TITLE
Not working in raspberry pi3

### ISSUE THREAD

**Issue by mvtcode** [sindresorhus/clipboardy#57]
When I using this module in raspberry pi3, has exception:

> Error: Both xsel and fallback failed
>     at makeError (/home/pi/test-rfid/node_modules/clipboardy/lib/linux.js:16:11)
>     at xselWithFallbackSync (/home/pi/test-rfid/node_modules/clipboardy/lib/linux.js:43:10)
>     at Object.copySync (/home/pi/test-rfid/node_modules/clipboardy/lib/linux.js:53:3)
>     at Object.exports.writeSync.text [as writeSync] (/home/pi/test-rfid/node_modules/clipboardy/index.js:39:14)
>     at Timeout._onTimeout (/home/pi/test-rfid/index.js:44:13)
>     at ontimeout (timers.js:436:11)
>     at tryOnTimeout (timers.js:300:5)
>     at listOnTimeout (timers.js:263:5)
>     at Timer.processTimers (timers.js:223:10)

**Comment by sinedied** [comment]
Same on ubuntu

**Comment by tahsinature** [comment]
please fix this problem
my machine: `#109-Ubuntu SMP Fri Nov 8 09:30:18 UTC 2019`

![download](https://user-images.githubusercontent.com/41298152/70219503-8483d200-1777-11ea-9568-2e4fb6c535ff.png)

**Comment by mifi** [comment]
what happens if you `apt-get install xsel`?

**Comment by sinedied** [comment]
@mifi tried to do that on Travis CI ubuntu image before running my tests, but it did not help.
