### ISSUE TITLE
Couldn't find the `xsel` binary and fallback didn't work.

### ISSUE THREAD

**Issue by eng-dibo** [sindresorhus/clipboardy#75]
I run `npx semantic-release-cli setup`, and I provided these configs
```
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? eng.dibo
? What is your npm password? [hidden]
? What is your NPM two-factor authentication code? 060355
```
but the following error occurred
OS: Debian GNU/Linux 10 (buster)
```
ERR! semantic-release Error: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel
ERR! semantic-release     at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:14:11)
ERR! semantic-release     at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:31:10)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:94:5)
ERR! semantic-release  Error: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel
ERR! semantic-release     at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:14:11)
ERR! semantic-release     at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:31:10)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:94:5) {
ERR! semantic-release   stack: "Error: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel\n" +
ERR! semantic-release     '    at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:14:11)\n' +
ERR! semantic-release     '    at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:31:10)\n' +
ERR! semantic-release     '    at processTicksAndRejections (internal/process/task_queues.js:94:5)',
ERR! semantic-release   fallbackError: Error: Command failed: /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel --clipboard --output
ERR! semantic-release   /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel: Can't open display: (null)
ERR! semantic-release   : Inappropriate ioctl for device
ERR! semantic-release   
ERR! semantic-release   
ERR! semantic-release       at makeError (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/execa/index.js:174:9)
ERR! semantic-release       at /home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/execa/index.js:278:16
ERR! semantic-release       at processTicksAndRejections (internal/process/task_queues.js:94:5)
ERR! semantic-release       at xselWithFallback (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/lib/linux.js:29:11)
ERR! semantic-release       at Object.default (/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/github.js:25:32) {
ERR! semantic-release     code: 1,
ERR! semantic-release     stdout: '',
ERR! semantic-release     stderr: "/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel: Can't open display: (null)\n" +
ERR! semantic-release       ': Inappropriate ioctl for device\n',
ERR! semantic-release     failed: true,
ERR! semantic-release     signal: null,
ERR! semantic-release     cmd: '/home/sh_eldeeb_2010/.npm/_npx/4b6729947d3d91fc/node_modules/clipboardy/fallbacks/linux/xsel --clipboard --output',
ERR! semantic-release     timedOut: false,
ERR! semantic-release     killed: false
ERR! semantic-release   }
ERR! semantic-release }
```

**Comment by eng-dibo** [comment]
closin issue for trying to install xsel with `sudo apt install xsel`
