### ISSUE TITLE
i tried running clipboard thru heroku and this is the error i encounter

### ISSUE THREAD

**Issue by kadistudio** [sindresorhus/clipboardy#88]
I have installed the xsel thru npm i xsel in my terminal before pushing it to github

error = new Error('Couldn\'t find the `xsel` binary and fallback didn\'t work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel');

Error: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel
at makeError (/app/node_modules/clipboardy/lib/linux.js:14:11)
at xselWithFallbackSync (/app/node_modules/clipboardy/lib/linux.js:43:10)
at Object.copySync (/app/node_modules/clipboardy/lib/linux.js:53:3)
at Object.exports.writeSync (/app/node_modules/clipboardy/index.js:45:14)
at InteractionCollector.<anonymous> (/app/Commands/Paimon Menu/namecard.js:442:43)
at InteractionCollector.emit (node:events:539:35)
at InteractionCollector.handleCollect (/app/node_modules/discord.js/src/structures/interfaces/Collector.js:109:12)
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
fallbackError: Error: spawnSync /app/node_modules/clipboardy/fallbacks/linux/xsel EACCES
at Object.spawnSync (node:internal/child_process:1109:20)
at Object.spawnSync (node:child_process:814:24)
at Function.module.exports.sync (/app/node_modules/clipboardy/node_modules/execa/index.js:334:30)
at xselWithFallbackSync (/app/node_modules/clipboardy/lib/linux.js:41:17)
at Object.copySync (/app/node_modules/clipboardy/lib/linux.js:53:3)
at Object.exports.writeSync (/app/node_modules/clipboardy/index.js:45:14)
at InteractionCollector.<anonymous> (/app/Commands/Paimon Menu/namecard.js:442:43)
at InteractionCollector.emit (node:events:539:35)
at InteractionCollector.handleCollect (/app/node_modules/discord.js/src/structures/interfaces/Collector.js:109:12)
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
errno: -13,
code: 'EACCES',
syscall: 'spawnSync /app/node_modules/clipboardy/fallbacks/linux/xsel',
path: '/app/node_modules/clipboardy/fallbacks/linux/xsel',
spawnargs: [ '--clipboard', '--input' ],
stdout: null,
stderr: null,
failed: true,
signal: null,
cmd: '/app/node_modules/clipboardy/fallbacks/linux/xsel --clipboard --input',
timedOut: false
}
}
Node.js v17.8.0

**Comment by sindresorhus** [comment]
I'm not sure why you're using this in Heroku, but you need to install in `xsel` in Heroku, not on your system to fix that error.
